on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Task (Linux/macOS)
      if: runner.os != 'Windows'
      run: curl -sL https://taskfile.dev/install.sh | sh
    - name: Install Task (Windows)
      if: runner.os == 'Windows'
      shell: powershell
      run: |
          Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
          scoop bucket add extras
          scoop install task
    - name: Run CI Task (Linux/macOS)
      if: runner.os != 'Windows'
      run: ./bin/task ci
    - name: Run CI Task (Windows)
      if: runner.os == 'Windows'
      run: task ci

